language: node_js
node_js:
  - "0.11"
  - "0.10"
matrix:
  allow_failures:
    - node_js: "0.11"
  fast_finish: true
script: "./node_modules/.bin/gulp test-coverage"
after_script: "cat ./coverage/lcov.info | coveralls"
